// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIMwx5TJ6qjwgrG8Oe7V2kjvSNx26RHes',
    appId: '1:1000584702350:web:a35cfd3bb252f4c5699cdf',
    messagingSenderId: '1000584702350',
    projectId: 'bloodbank-393b6',
    authDomain: 'bloodbank-393b6.firebaseapp.com',
    databaseURL: 'https://bloodbank-393b6-default-rtdb.firebaseio.com',
    storageBucket: 'bloodbank-393b6.appspot.com',
    measurementId: 'G-X64ZNQVEE1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg88hVuikV7GB6Y2p7-WA5jx-kOz8agqY',
    appId: '1:1000584702350:android:71be4958006f090e699cdf',
    messagingSenderId: '1000584702350',
    projectId: 'bloodbank-393b6',
    databaseURL: 'https://bloodbank-393b6-default-rtdb.firebaseio.com',
    storageBucket: 'bloodbank-393b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp7FEwsaYC5khEIQTwyA5Cm-BBE9hPsQA',
    appId: '1:1000584702350:ios:871b6919b792627a699cdf',
    messagingSenderId: '1000584702350',
    projectId: 'bloodbank-393b6',
    databaseURL: 'https://bloodbank-393b6-default-rtdb.firebaseio.com',
    storageBucket: 'bloodbank-393b6.appspot.com',
    iosBundleId: 'com.example.bloodBond',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp7FEwsaYC5khEIQTwyA5Cm-BBE9hPsQA',
    appId: '1:1000584702350:ios:871b6919b792627a699cdf',
    messagingSenderId: '1000584702350',
    projectId: 'bloodbank-393b6',
    databaseURL: 'https://bloodbank-393b6-default-rtdb.firebaseio.com',
    storageBucket: 'bloodbank-393b6.appspot.com',
    iosBundleId: 'com.example.bloodBond',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJHk330qdU7Vs8f8FwN6WtcFa7PSBGfyY',
    appId: '1:1000584702350:web:3a5f6e56a8f4bcdd699cdf',
    messagingSenderId: '1000584702350',
    projectId: 'bloodbank-393b6',
    authDomain: 'bloodbank-393b6.firebaseapp.com',
    databaseURL: 'https://bloodbank-393b6-default-rtdb.firebaseio.com',
    storageBucket: 'bloodbank-393b6.appspot.com',
    measurementId: 'G-B9VY0RSLCP',
  );

}